name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  MYSQL_PASSWORD: horizon
  MYSQL_USERNAME: root
  MYSQL_DATABASE: horizon
  MYSQL_HOSTNAME: localhost

jobs:
  cluster-dependencies:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: self-hosted

    steps:
    - name: VCPKG Install
      run: vcpkg install vcpkg-cmake:x64-windows readline:x64-windows lua:x64-windows zlib:x64-windows sol2:x64-windows libmysql:x64-windows mysql-connector-cpp:x64-windows
    
    - name: VCPKG Install Boost
      run: vcpkg install boost-log:x64-windows boost-filesystem:x64-windows boost-system:x64-windows boost-test:x64-windows boost-locale:x64-windows boost-crc:x64-windows boost-multi-array:x64-windows

    - name : VCPKG Integrate
      run: vcpkg integrate install

  testing:
    needs: cluster-dependencies
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: sh ./horizon.sh build-tests -DCMAKE_INSTALL_PREFIX="${{github.workspace}}\build" -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows;
    - name: Run
      run: sh ./horizon.sh run-tests "build\test\Release";
  build-install-and-run:
    needs: testing
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure Step & Build
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: sh ./horizon.sh build ${{github.workspace}}\build -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}\build" ; 
    - name: Install
      run: sh ./horizon.sh install "build/bin/Release";
    - name: Install Database
      run: sh ./horizon.sh createdb ${{env.MYSQL_USERNAME}} ${{env.MYSQL_PASSWORD}} ${{env.MYSQL_HOSTNAME}} ${{env.MYSQL_DATABASE}};
           sh ./horizon.sh importdb ${{env.MYSQL_USERNAME}} ${{env.MYSQL_PASSWORD}} ${{env.MYSQL_HOSTNAME}} ${{env.MYSQL_DATABASE}};
           sh ./horizon.sh adduser ${{env.MYSQL_USERNAME}} ${{env.MYSQL_PASSWORD}} ${{env.MYSQL_HOSTNAME}} ${{env.MYSQL_DATABASE}} horizon horizon;
    - name: Run
      run: sh ./horizon.sh auth build\bin\Release --with-config="build\bin\Release\config\auth-server.lua" --test-run;
           sh ./horizon.sh char build\bin\Release --with-config="build\bin\Release\config\char-server.lua" --test-run;
           sh ./horizon.sh zone build\bin\Release --with-config="build\bin\Release\config\zone-server.lua" --test-run;
      
  cleanup:
    needs: build-install-and-run
    runs-on: self-hosted
    steps:
    - name: Cleanup
      run: sh ./horizon.sh dropdb horizon ${{env.MYSQL_USERNAME}} ${{env.MYSQL_PASSWORD}};
