name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: VCPKG Install
      run: vcpkg install vcpkg-cmake:x64-windows readline:x64-windows lua:x64-windows zlib:x64-windows sol2:x64-windows libmysql:x64-windows mysql-connector-cpp:x64-windows
    
    - name: VCPKG Install Boost
      run: vcpkg install boost-log:x64-windows boost-filesystem:x64-windows boost-system:x64-windows boost-test:x64-windows boost-locale:x64-windows boost-crc:x64-windows boost-multi-array:x64-windows

    - name : VCPKG Integrate
      run: vcpkg integrate install
    
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}\build -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}\horizon-bin" 

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}\build --config ${{env.BUILD_TYPE}}

    - name: Run Build
      run: cp ${{ github.workspace }}\db ${{github.workspace}}\horizon-bin
           cp ${{ github.workspace }}\config ${{github.workspace}}\horizon-bin 
           cp ${{ github.workspace }}\scripts ${{github.workspace}}\horizon-bin 
           mv ${{ github.workspace }}\auth-server.lua.dist ${{ github.workspace }}\horizon-bin\config\auth-server.lua
           mv ${{ github.workspace }}\char-server.lua.dist ${{ github.workspace }}\horizon-bin\config\char-server.lua
           mv ${{ github.workspace }}\zone-server.lua.dist ${{ github.workspace }}\horizon-bin\config\zone-server.lua
           ${{ github.workspace }}\horizon-bin\auth.exe --config="config/auth-server.lua"
           ${{ github.workspace }}\horizon-bin\char.exe --config="config/char-server.lua"
           ${{ github.workspace }}\horizon-bin\zone.exe --config="config/zone-server.lua"
    - name: Test
      working-directory: ${{github.workspace}}\build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}

